//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;

    public partial class Nurses_PlacementEntities : DbContext
    {
        public Nurses_PlacementEntities()
        : base("name=Nurses_PlacementEntities")
        {
            base.Configuration.ProxyCreationEnabled = false;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public List<T> GetDbSet<T>() where T : class
        {

            return Set<T>().ToList();
        }


        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Nurse> Nurses { get; set; }
        public virtual DbSet<NursesInDepartment> NursesInDepartments { get; set; }
        public virtual DbSet<Placement> Placements { get; set; }
    }
}
