//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NursesInDepartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NursesInDepartment()
        {
            this.Placements = new HashSet<Placement>();
        }
    
        public int ND_id_NinD { get; set; }
        public Nullable<int> ND_D_id { get; set; }
        public string ND_N_id { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Nurse Nurse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Placement> Placements { get; set; }
    }
}
