//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nurse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nurse()
        {
            this.NursesInDepartments = new HashSet<NursesInDepartment>();
        }
    
        public string N_id { get; set; }
        public string N_password { get; set; }
        public string N_firstName { get; set; }
        public string N_lastName { get; set; }
        public string N_tel { get; set; }
        public string N_email { get; set; }
        public string N_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NursesInDepartment> NursesInDepartments { get; set; }
    }
}
