//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Placement
    {
        public int P_id { get; set; }
        public Nullable<int> P_idNInD { get; set; }
        public Nullable<int> P_day { get; set; }
        public string P_shift { get; set; }
    
        public virtual NursesInDepartment NursesInDepartment { get; set; }
    }
}
